### ISSUE TITLE
Near line 10 (last key parsed 'listen'): expected a comma or array terminator ']', but got ':' instead

### ISSUE THREAD

**Issue by OdinGitDat** [satishweb/docker-doh#12]
For some reason the environment variables are not applied correctly. This is my compose: 
```
version: "3"

services:
  doh-server:
    image: satishweb/doh-server
    environment:
      - UPSTREAM_DNS_SERVER="udp:pihole:53"
      - DOH_HTTP_PREFIX="/dns-query"
      - DOH_SERVER_LISTEN=":8053"
```

log reports this:
```
|---------------------------------------------------------------------------------------------
| Starting DNS Over HTTP Service 
| ENTRYPOINT: Loading docker secrets if found...
| ENTRYPOINT: app-config was not available, running given parameters or default CMD...
2022/03/04 16:35:43 Near line 10 (last key parsed 'listen'): expected a comma or array terminator ']', but got ':' instead
```
and
```
2022/03/04 16:40:19 Near line 28 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '/' instead
```
